// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2rLY4ibAPpNL1BHjbfDnfJ-ihaO5zTIA',
    appId: '1:173591083829:web:3623ec15983fb91fd9aa7c',
    messagingSenderId: '173591083829',
    projectId: 'planning-all-pepe-rosa-923c7',
    authDomain: 'planning-all-pepe-rosa-923c7.firebaseapp.com',
    storageBucket: 'planning-all-pepe-rosa-923c7.firebasestorage.app',
    measurementId: 'G-EGGEJ1L8Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyTPfrUn2mREdN7fDeIfOQwzhkAmkIKtU',
    appId: '1:173591083829:android:d96dfe2e60b9ce2bd9aa7c',
    messagingSenderId: '173591083829',
    projectId: 'planning-all-pepe-rosa-923c7',
    storageBucket: 'planning-all-pepe-rosa-923c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFNMTKWpnZBbv-j1_-UZ7Hp0jLXfhNMc',
    appId: '1:173591083829:ios:fbd737c40cceb3fad9aa7c',
    messagingSenderId: '173591083829',
    projectId: 'planning-all-pepe-rosa-923c7',
    storageBucket: 'planning-all-pepe-rosa-923c7.firebasestorage.app',
    iosBundleId: 'com.example.testFotocamera2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzFNMTKWpnZBbv-j1_-UZ7Hp0jLXfhNMc',
    appId: '1:173591083829:ios:fbd737c40cceb3fad9aa7c',
    messagingSenderId: '173591083829',
    projectId: 'planning-all-pepe-rosa-923c7',
    storageBucket: 'planning-all-pepe-rosa-923c7.firebasestorage.app',
    iosBundleId: 'com.example.testFotocamera2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2rLY4ibAPpNL1BHjbfDnfJ-ihaO5zTIA',
    appId: '1:173591083829:web:afb1a45e83747470d9aa7c',
    messagingSenderId: '173591083829',
    projectId: 'planning-all-pepe-rosa-923c7',
    authDomain: 'planning-all-pepe-rosa-923c7.firebaseapp.com',
    storageBucket: 'planning-all-pepe-rosa-923c7.firebasestorage.app',
    measurementId: 'G-CR9P5Z8RGS',
  );

}