// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpHkkt7GlX-qIUvCyQiwYCcdQHxUZZA5Y',
    appId: '1:394570910879:web:1f5db25ee90f2572c126aa',
    messagingSenderId: '394570910879',
    projectId: 'peperosa-planning-v2',
    authDomain: 'peperosa-planning-v2.firebaseapp.com',
    storageBucket: 'peperosa-planning-v2.firebasestorage.app',
    measurementId: 'G-VKWCMKM4V3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNHCih2rA4U0Wd-_VLZJPXcj4be2wiiU',
    appId: '1:394570910879:android:72deab5455800825c126aa',
    messagingSenderId: '394570910879',
    projectId: 'peperosa-planning-v2',
    storageBucket: 'peperosa-planning-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN3se5o7t9-uPwUIZDQnaRRuRHUMu83tE',
    appId: '1:394570910879:ios:04d7fafff8fb5588c126aa',
    messagingSenderId: '394570910879',
    projectId: 'peperosa-planning-v2',
    storageBucket: 'peperosa-planning-v2.firebasestorage.app',
    iosBundleId: 'com.example.testFotocamera2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN3se5o7t9-uPwUIZDQnaRRuRHUMu83tE',
    appId: '1:394570910879:ios:04d7fafff8fb5588c126aa',
    messagingSenderId: '394570910879',
    projectId: 'peperosa-planning-v2',
    storageBucket: 'peperosa-planning-v2.firebasestorage.app',
    iosBundleId: 'com.example.testFotocamera2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpHkkt7GlX-qIUvCyQiwYCcdQHxUZZA5Y',
    appId: '1:394570910879:web:e3b9ffc2ce852fe1c126aa',
    messagingSenderId: '394570910879',
    projectId: 'peperosa-planning-v2',
    authDomain: 'peperosa-planning-v2.firebaseapp.com',
    storageBucket: 'peperosa-planning-v2.firebasestorage.app',
    measurementId: 'G-05XSY4S2QK',
  );

}